services:
  db:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password123'
      POSTGRES_DB: 'ny_taxi'
    ports:
      - '5433:5432'
    volumes:
      - ny_taxi_db_storage:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pg@admin.com'
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "8080:80"
    volumes:
      - ny_taxi_pgadmin_storage:/var/lib/pgadmin

volumes:
  ny_taxi_db_storage:
    name: ny_taxi_db_storage
  ny_taxi_pgadmin_storage:
    name: ny_taxi_pgadmin_storage